config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/auth/:provider/callback', to: 'sessions#create'

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#home' # theses#index
    resources :users do
      resources :theses do
        member do
          post :bookmark
        end
      end
    end
    get 'search', to: 'theses#search'
    resources :theses, only: [:index, :new, :create, :search, :pdf]
    resources :schools, only: [ :index, :show, :edit, :update ]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :theses, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:twitter]

  # Omniauth Twitter
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.uid.to_s+'@twitter.com'
      user.image = auth.info.image
    end
  end

  # Authentication token
  acts_as_token_authenticatable
  # Bookmarks : voter
  acts_as_voter

  # Associations
  belongs_to :school
  has_many :theses, dependent: :destroy

  # Validations
  validates :email, :password, presence: true
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token

  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      if session[:thesis_title]
        title = session[:thesis_title]
        subtitle = session[:thesis_subtitle]
        school = session[:thesis_school_id]
        diploma_id = session[:thesis_diploma_id]
        year = session[:thesis_year]
        tags = session[:thesis_tags]
        thesis = Thesis.new(title: title, subtitle: subtitle, year: year, school: School.find(session[:thesis_school_id]) )
        thesis.user = resource
        thesis.tag_list.add(tags, parse: true)
        thesis.diploma = Diploma.find(diploma_id)
        thesis.save
        session_cleaner
      end

      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")

      puts @user.errors

      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show ]
  skip_before_action :authenticate_user!, only: [ :show ]
  layout "basic"

  def show
    @theses = @user.theses
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    @user = current_user
    authorize @user
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :bio, :birthdate, :website)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<main class="container" id="dashboard-wrapper">
  <div class="row gutters" id="dashboard">

    <div class="col col-3 profil">
      <div class="user-avatar">
        <%= image_tag "timothee.jpg", class:"avatar-full rounded" %>
      </div>
    </div>

    <!-- Tabs -->
    <div class="col col-8">
      <nav class="tabs" data-component="tabs">
        <ul class="row gutters">
          <div class="col">
            <li>
              <a href="#profile">
                <i class='material-icons md-18'>account_circle</i>
                <%= t('.profile_tab_title_my_account') %>
              </a>
            </li>
          </div>
          <div class="col">
            <li>
              <a href="#theses">
                <i class='material-icons md-18'>book</i>
                <%= t('.thesis_tab_title_my_account') %>
              </a>
            </li>
          </div>
          <div class="col">
            <li>
              <a href="#bookmarks">
                <i class='material-icons md-18'>turned_in</i>
                <%= t('.bookmarks_tab_title_my_account') %>
              </a>
            </li>
          </div>
          <% if policy(@user).edit? %>
            <div class="col">
              <li>
                <a href="#settings"><i class='material-icons md-18'>settings</i> <%= t('.settings_tab_my_account') %></a>
              </li>
            </div>
          <% end %>
        </ul>
      </nav>

      <!-- My profile -->
      <div class="tab-content" id="profile">
        <fieldset>
          <legend><%= t('.edit_your_profile') %></legend>
          <%= simple_form_for(current_user, defaults: { wrapper_html: { class: 'form-item'} }, html: { class: "form" }) do |f| %>
            <%= f.input :email, label: t('.email') %>
            <%= f.input :first_name, label: t('.first_name'), class: "user-name" %>
            <%= f.input :last_name, label: t('.last_name'), class: "user-name" %>
            <%= f.input :bio, label: t('.bio'), class: "user-bio" %>
            <%= f.input :website, label: t('.website'), class: "user-website" %>
            <%= f.input :birthdate, label: t('.birthdate'), class: "user-birthdate" %>
            <%= f.submit t('.save'), class: "button secondary big upper" %>
          <% end %>
        </fieldset>
      </div>
    </div>
  </div>

</main>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      jQuery(".best_in_place").best_in_place();
    });
  <% end %>
<% end %>

app/views/users/show.html.erb
<main class="container" id="dashboard-wrapper">
  <div class="row gutters" id="dashboard">

    <div class="col col-3 user-avatar">
      <%= image_tag "timothee.jpg", class:"avatar-full rounded" %>
    </div>

    <!-- Tabs -->
    <div class="col col-8">
      <nav class="tabs" data-component="tabs">
        <ul class="row gutters">
          <div class="col">
            <li>
              <a href="#profile">
                <i class='material-icons md-18'>account_circle</i>
                <%= @user == current_user ? t('.profile_tab_title_my_account') : t('.profile_tab_title') %>
              </a>
            </li>
          </div>
          <div class="col">
            <li>
              <a href="#theses">
                <i class='material-icons md-18'>book</i>
                <%= @user == current_user ? t('.thesis_tab_title_my_account') : t('.thesis_tab_title') %>
              </a>
            </li>
          </div>
          <div class="col">
            <li>
              <a href="#bookmarks">
                <i class='material-icons md-18'>turned_in</i>
                <%= @user == current_user ? t('.bookmarks_tab_title_my_account') : t('.bookmarks_tab_title') %>
                <%= '(' + @user.find_voted_items.count.to_s + ')' unless @user.find_voted_items.count.zero? || @user.find_voted_items.count.nil? %>
              </a>
            </li>
          </div>
          <% if policy(@user).edit? %>
            <div class="col">
              <li>
                <a href="#settings"><i class='material-icons md-18'>settings</i> <%= t('.settings_tab_my_account') %></a>
              </li>
            </div>
          <% end %>
        </ul>
      </nav>

      <!-- My profile -->
      <div class="tab-content" id="profile">
        <fieldset>
          <div class="user-data">
            <h2 class="user-name"><strong><%= @user.first_name %> <%= @user.last_name %></strong></h2>
            <p class="user-bio"><%= @user.bio %></p>
            <p class="user-website">
              <%= link_to @user.website, @user.website, class: "underline" %>
            </p>
          </div>
          <% if policy(@user).edit? %>
            <%= link_to t('.edit') , edit_user_path(current_user), id: "edit", class: "button small upper secondary" %>
          <% end %>
        </fieldset>
      </div>

      <!-- My thesis -->
      <div class="tab-content" id="theses">
        <div id="cards" class="cards">
          <%= render "shared/cards", theses: @theses %>
        </div>
      </div>

      <!-- My bookmarks -->
      <div class="tab-content" id="bookmarks">
        <% if @user.find_voted_items.count == 0 %>
          <h3><%= t('.no_bookmark_text') %></h3>
          <%= link_to t('.explore_link'), theses_path, class: "button outline secondary" %>
        <% else %>
          <div id="cards" class="cards">
            <%= render "shared/cards", theses: @user.find_voted_items %>
          </div>
        <% end %>
      </div>

      <!-- Settings & privacy -->
      <% if policy(@user).edit? %>
        <div class="tab-content" id="settings">
          <h3><%= t('.permission') %></h3>
        </div>
      <% end %>
    </div>
  </div>

</main>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>