config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/auth/:provider/callback', to: 'sessions#create'

  scope '(:locale)', locale: /fr|en/ do
    root to: 'pages#home' # theses#index
    resources :users do
      resources :theses do
        member do
          post :bookmark
        end
      end
    end
    get 'search', to: 'theses#search'
    resources :theses, only: [:index, :new, :create, :search, :pdf]
    resources :schools, only: [ :index, :show, :edit, :update ]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :theses, only: [ :index, :show, :update, :create, :destroy ]
    end
  end
end

app/views/pages/home.html.erb
<main class="container full", id="main">

  <section class="hero">
    <div id="intro" class="z200">
      <h1>mnémosyne</h1>
      <h2>
        <%= t('.tagline_1') %><br><%= t('.tagline_2')%> d’<span class="categories">
          <% Thesis::CATEGORIES.each do |category| %>
            <%= link_to category.gsub("-", " "), search_path(keywords: category.gsub("-", " ")), id: category, class: "home-category" %>
          <% end %>
        </span>
      </h2>
      <%= link_to t('.button_theses_index'), theses_path, class: "button outline upper secondary large margin-big" %>
    </div>
    <%= image_tag asset_path("covers/2013-mickael_cuillerat-l_avenir_des_villes_musees.jpg"), {class: "home-cover shadow", id: "cover-1"} %>
    <%= image_tag asset_path("covers/2016-antoine_omerin-wesh_alors.jpg"), {class: "home-cover shadow", id: "cover-2"} %>
  </section>

  <!-- <section class="hero">
    <h2>Mémoires récents</h2>
    <div id="cards" class="cards z100">
      <%#= render "shared/cards", theses: Thesis.last(5) %>
    </div>
  </section> -->

</main>

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function(event) {
    alert(
      "👉 Ce site est une version démo réalisée en 10 jours dans le cadre du programme de formation FullStack proposé par @LeWagonParis.\n\n"
      + "⚠️ Toute la base de donnée de mémoires et d’utilisateurs a été générée à cette occasion et sera donc très prochainement effacée pour la mise en ligne de la version alpha sur invitation.\n\n"
      + "✉️ Pour toute question, merci de me contacter à timothee@mnemosyne.io\n\n"
      + "👍 Merci de votre compréhension et bonne exploration !\n\n\n"
      + "👨‍💻 — Timothée"
    );
  });
</script>